spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:products}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:products}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
