server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/abarrotes_orders?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    activate:
      on-profile: docker
  cloud:
    discovery:
      enabled: false

# Eureka Client Disabled for Docker profile
eureka:
  client:
    enabled: false

---
# Perfil Docker para Logs Estructurados
spring:
  config:
    activate:
      on-profile: docker
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO